# Generated by Django 4.0.1 on 2022-02-28 23:17

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.CharField(max_length=60, verbose_name='Телефонный номер')),
                ('gender', models.IntegerField(choices=[(1, 'Мужчина'), (2, 'Женщина'), (3, 'Программист')], verbose_name='Гендер')),
                ('occupation', models.CharField(choices=[('STUDENT', 'Студент'), ('WORKER', 'Работающий'), ('JOBLESS', 'Без работы'), ('RETIRED', 'Пенсионер'), ('MILLIONAIRE', 'Миллионер')], max_length=80)),
                ('birth_year', models.CharField(max_length=10, verbose_name='Год рождения')),
                ('github_nickname', models.CharField(max_length=80, verbose_name='Никнейм в Гитхабе')),
                ('continent', models.CharField(choices=[('NORTH AMERICA', 'Северная Америка'), ('SOUTH AMERICA', 'Южная Америка'), ('EUROPE', 'Европа'), ('AFRICA', 'Африка'), ('ANTARCTICA', 'Антарктика'), ('ASIA', 'Азия'), ('AUSTRALIA', 'Австралия')], max_length=80)),
                ('mobile_operator', models.CharField(choices=[('BEELINE', 'Билайн'), ('OSHKA', 'О!'), ('MEGACOM', 'Мегаком')], max_length=20)),
                ('fav_anime_site', models.CharField(choices=[('YUMMYANIME', 'YummyAnime'), ('ANIMEKISA', 'AnimeKisa'), ('ANIMEVOSTORG', 'Anime VostOrg'), ('JUTSU', 'JutSu'), ('WAKANIM', 'Wakanim'), ('CRUNCHYROLL', 'Crunchyroll'), ('FUNIMATION', 'Funimation')], max_length=50)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
