# Generated by Django 4.0.1 on 2022-02-28 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='github_nickname',
            field=models.CharField(max_length=80, unique=True, verbose_name='Никнейм в Гитхабе'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=60, unique=True, verbose_name='Телефонный номер'),
        ),
    ]
